"""Translates Markdown structure into structured Accounts."""

import re
from typing import Iterator

from core.models import FinancialAccount, SourceType


class MarkdownParser:
    """Parses structural tables generated by MarkItDown."""

    def __init__(self):
        # Captures generalized row lines: | Description | Value | Value | ...
        self.md_table_pattern = re.compile(r"\|(.*?)\|(.*?)\|(?:\s*\|\s*)*")

    def parse(self, markdown_text: str, period: str, section: str = "UNKNOWN") -> Iterator[FinancialAccount]:
        """
        Takes raw string from MarkItDown. Identifies table lines and yields FinancialAccounts.
        Since parsing is fuzzy, confidence is lowered natively.
        """
        for line in markdown_text.splitlines():
            line = line.strip()
            if not line.startswith("|") or "---" in line:
                continue
                
            match = self.md_table_pattern.match(line)
            if not match:
                continue

            desc_raw = match.group(1).strip()
            val_raw = match.group(2).strip()

            from .normalizer import normalize_financial_value
            value = normalize_financial_value(val_raw)

            if desc_raw and value is not None:
                # PDF extracted elements typically don't have code identifiers and confidence fluctuates.
                yield FinancialAccount(
                    code=None,  
                    description=desc_raw,
                    value=value,
                    period=period,
                    section=section,
                    source=SourceType.PDF,
                    confidence=0.80  # Default OCR degradation
                )
